research_task:
  description: >
    {topic}에 대해 철저한 조사를 수행하세요.
    현재 연도인 {current_year}를 기준으로 흥미롭고 관련성 높은 정보를 반드시 찾아야 합니다.
  expected_output: >
    1. {topic}에 대한 가장 핵심적인 정보를 담은 10개의 글머리표 목록
    2. 한국어로 작성
  agent: researcher

reporting_task:
  description: >
    이전에 수집한 내용을 검토하고, 각 항목을 전체 보고서의 개별 섹션으로 확장하세요.
    보고서는 상세해야 하며, 관련된 모든 정보가 포함되어야 합니다.
  expected_output: >
    1. 주요 주제별로 전체 섹션이 구성된 완전한 보고서.
    2. 마크다운 형식으로 작성하되, 코드 블록 표시인 '```'는 사용하지 마세요.
    3. 1000자 내로 요약
    4. 한국어로 작성
  agent: reporting_analyst
